### ISSUE TITLE
Travis CI wont run th tests

### ISSUE THREAD

**Issue by jankapunkt** [jankapunkt/meteor-autoform-bpmn#10]
While local tests run fine, travis wont even start a test due to 

`Error: Cannot find module '@babel/runtime/helpers/builtin/interopRequireDefault'`

babel runtime is

` "@babel/runtime": "^7.0.0-beta.55",`

https://travis-ci.org/jankapunkt/meteor-autoform-bpmn/

Somebody has any clue how to fix it?

**Comment by jankapunkt** [comment]
Babel runtime issue is resolved but now I have the issue, that chromedriver is not providing the sufficient chrome version for selenium (although it is the correct installed chromedriver version)

```
W20180813-19:17:10.852(0)? (STDERR) /home/travis/build/jankapunkt/meteor-autoform-bpmn/testing/node_modules/selenium-webdriver/lib/promise.js:2626
W20180813-19:17:10.852(0)? (STDERR)         throw error;
W20180813-19:17:10.853(0)? (STDERR)         ^
W20180813-19:17:10.853(0)? (STDERR) 
W20180813-19:17:10.853(0)? (STDERR) SessionNotCreatedError: session not created exception: Chrome version must be >= 67.0.3396.0
W20180813-19:17:10.866(0)? (STDERR)   (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.4.0-101-generic x86_64)
W20180813-19:17:10.867(0)? (STDERR)     at Object.checkLegacyResponse (/home/travis/build/jankapunkt/meteor-autoform-bpmn/testing/node_modules/selenium-webdriver/lib/error.js:546:15)
W20180813-19:17:10.867(0)? (STDERR)     at parseHttpResponse (/home/travis/build/jankapunkt/meteor-autoform-bpmn/testing/node_modules/selenium-webdriver/lib/http.js:509:13)
W20180813-19:17:10.867(0)? (STDERR)     at doSend.then.response (/home/travis/build/jankapunkt/meteor-autoform-bpmn/testing/node_modules/selenium-webdriver/lib/http.js:441:30)
W20180813-19:17:10.868(0)? (STDERR)     at /home/travis/.meteor/packages/promise/.0.11.1.1q584qp.8ndl++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20180813-19:17:10.868(0)? (STDERR) From: Task: WebDriver.createSession()
W20180813-19:17:10.868(0)? (STDERR)     at Function.createSession (/home/travis/build/jankapunkt/meteor-autoform-bpmn/testing/node_modules/selenium-webdriver/lib/webdriver.js:769:24)
W20180813-19:17:10.869(0)? (STDERR)     at Function.createSession (/home/travis/build/jankapunkt/meteor-autoform-bpmn/testing/node_modules/selenium-webdriver/chrome.js:761:15)
W20180813-19:17:10.869(0)? (STDERR)     at createDriver (/home/travis/build/jankapunkt/meteor-autoform-bpmn/testing/node_modules/selenium-webdriver/index.js:170:33)
W20180813-19:17:10.870(0)? (STDERR)     at Builder.build (/home/travis/build/jankapunkt/meteor-autoform-bpmn/testing/node_modules/selenium-webdriver/index.js:642:16)
W20180813-19:17:10.870(0)? (STDERR)     at startChrome (packages/meteortesting:browser-tests/browser/chromedriver.js:46:136)
W20180813-19:17:10.870(0)? (STDERR)     at startBrowser (packages/meteortesting:browser-tests/server.js:23:7)
W20180813-19:17:10.871(0)? (STDERR)     at clientTests (packages/meteortesting:mocha/server.js:138:3)
W20180813-19:17:10.871(0)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:168:7)
W20180813-19:17:10.872(0)? (STDERR)     at serverTests (packages/meteortesting:mocha/server.js:94:13)
W20180813-19:17:10.872(0)? (STDERR)     at Object.start (packages/meteortesting:mocha/server.js:167:5)
W20180813-19:17:10.873(0)? (STDERR)     at packages/meteor.js:1225:27
W20180813-19:17:10.873(0)? (STDERR)     at Function.time (/tmp/meteor-test-runhnwy7x.0u8s8/.meteor/local/build/programs/server/profile.js:309:28)
W20180813-19:17:10.874(0)? (STDERR)     at /tmp/meteor-test-runhnwy7x.0u8s8/.meteor/local/build/programs/server/boot.js:427:13
W20180813-19:17:10.874(0)? (STDERR)     at /tmp/meteor-test-runhnwy7x.0u8s8/.meteor/local/build/programs/server/boot.js:472:5
W20180813-19:17:10.875(0)? (STDERR)     at Function.run (/tmp/meteor-test-runhnwy7x.0u8s8/.meteor/local/build/programs/server/profile.js:510:12)
W20180813-19:17:10.875(0)? (STDERR)     at /tmp/meteor-test-runhnwy7x.0u8s8/.meteor/local/build/programs/server/boot.js:470:11
```
